/*
 * imx25 pinctrl driver.
 *
 * Copyright 2013 Eukréa Electromatique <denis@eukrea.com>
 *
 * This driver was mostly copied from the imx51 pinctrl driver which has:
 *
 * Copyright (C) 2012 Freescale Semiconductor, Inc.
 * Copyright (C) 2012 Linaro, Inc.
 *
 * Author: Denis Carikli <denis@eukrea.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation.
 */

#include <linux/err.h>
#include <linux/init.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-imx.h"
#include "../../arch/arm/mach-imx/iomux-mx25.h"

enum imx25_pads {
	MX25_PAD_RESERVE0 = 1,
	MX25_PAD_A10 = 2,
	MX25_PAD_A13 = 3,
	MX25_PAD_A14 = 4,
	MX25_PAD_A15 = 5,
	MX25_PAD_A16 = 6,
	MX25_PAD_A17 = 7,
	MX25_PAD_A18 = 8,
	MX25_PAD_A19 = 9,
	MX25_PAD_A20 = 10,
	MX25_PAD_A21 = 11,
	MX25_PAD_A22 = 12,
	MX25_PAD_A23 = 13,
	MX25_PAD_A24 = 14,
	MX25_PAD_A25 = 15,
	MX25_PAD_EB0 = 16,
	MX25_PAD_EB1 = 17,
	MX25_PAD_OE = 18,
	MX25_PAD_CS0 = 19,
	MX25_PAD_CS1 = 20,
	MX25_PAD_CS4 = 21,
	MX25_PAD_CS5 = 22,
	MX25_PAD_NF_CE0 = 23,
	MX25_PAD_ECB = 24,
	MX25_PAD_LBA = 25,
	MX25_PAD_BCLK = 26,
	MX25_PAD_RW = 27,
	MX25_PAD_NFWE_B = 28,
	MX25_PAD_NFRE_B = 29,
	MX25_PAD_NFALE = 30,
	MX25_PAD_NFCLE = 31,
	MX25_PAD_NFWP_B = 32,
	MX25_PAD_NFRB = 33,
	MX25_PAD_D15 = 34,
	MX25_PAD_D14 = 35,
	MX25_PAD_D13 = 36,
	MX25_PAD_D12 = 37,
	MX25_PAD_D11 = 38,
	MX25_PAD_D10 = 39,
	MX25_PAD_D9 = 40,
	MX25_PAD_D8 = 41,
	MX25_PAD_D7 = 42,
	MX25_PAD_D6 = 43,
	MX25_PAD_D5 = 44,
	MX25_PAD_D4 = 45,
	MX25_PAD_D3 = 46,
	MX25_PAD_D2 = 47,
	MX25_PAD_D1 = 48,
	MX25_PAD_D0 = 49,
	MX25_PAD_LD0 = 50,
	MX25_PAD_LD1 = 51,
	MX25_PAD_LD2 = 52,
	MX25_PAD_LD3 = 53,
	MX25_PAD_LD4 = 54,
	MX25_PAD_LD5 = 55,
	MX25_PAD_LD6 = 56,
	MX25_PAD_LD7 = 57,
	MX25_PAD_LD8 = 58,
	MX25_PAD_LD9 = 59,
	MX25_PAD_LD10 = 60,
	MX25_PAD_LD11 = 61,
	MX25_PAD_LD12 = 62,
	MX25_PAD_LD13 = 63,
	MX25_PAD_LD14 = 64,
	MX25_PAD_LD15 = 65,
	MX25_PAD_HSYNC = 66,
	MX25_PAD_VSYNC = 67,
	MX25_PAD_LSCLK = 68,
	MX25_PAD_OE_ACD = 69,
	MX25_PAD_CONTRAST = 70,
	MX25_PAD_PWM = 71,
	MX25_PAD_CSI_D2 = 72,
	MX25_PAD_CSI_D3 = 73,
	MX25_PAD_CSI_D4 = 74,
	MX25_PAD_CSI_D5 = 75,
	MX25_PAD_CSI_D6 = 76,
	MX25_PAD_CSI_D7 = 77,
	MX25_PAD_CSI_D8 = 78,
	MX25_PAD_CSI_D9 = 79,
	MX25_PAD_CSI_MCLK = 80,
	MX25_PAD_CSI_VSYNC = 81,
	MX25_PAD_CSI_HSYNC = 82,
	MX25_PAD_CSI_PIXCLK = 83,
	MX25_PAD_I2C1_CLK = 84,
	MX25_PAD_I2C1_DAT = 85,
	MX25_PAD_CSPI1_MOSI = 86,
	MX25_PAD_CSPI1_MISO = 87,
	MX25_PAD_CSPI1_SS0 = 88,
	MX25_PAD_CSPI1_SS1 = 89,
	MX25_PAD_CSPI1_SCLK = 90,
	MX25_PAD_CSPI1_RDY = 91,
	MX25_PAD_UART1_RXD = 92,
	MX25_PAD_UART1_TXD = 93,
	MX25_PAD_UART1_RTS = 94,
	MX25_PAD_UART1_CTS = 95,
	MX25_PAD_UART2_RXD = 96,
	MX25_PAD_UART2_TXD = 97,
	MX25_PAD_UART2_RTS = 98,
	MX25_PAD_UART2_CTS = 99,
	MX25_PAD_SD1_CMD = 100,
	MX25_PAD_SD1_CLK = 101,
	MX25_PAD_SD1_DATA0 = 102,
	MX25_PAD_SD1_DATA1 = 103,
	MX25_PAD_SD1_DATA2 = 104,
	MX25_PAD_SD1_DATA3 = 105,
	MX25_PAD_KPP_ROW0 = 106,
	MX25_PAD_KPP_ROW1 = 107,
	MX25_PAD_KPP_ROW2 = 108,
	MX25_PAD_KPP_ROW3 = 109,
	MX25_PAD_KPP_COL0 = 110,
	MX25_PAD_KPP_COL1 = 111,
	MX25_PAD_KPP_COL2 = 112,
	MX25_PAD_KPP_COL3 = 113,
	MX25_PAD_FEC_MDC = 114,
	MX25_PAD_FEC_MDIO = 115,
	MX25_PAD_FEC_TDATA0 = 116,
	MX25_PAD_FEC_TDATA1 = 117,
	MX25_PAD_FEC_TX_EN = 118,
	MX25_PAD_FEC_RDATA0 = 119,
	MX25_PAD_FEC_RDATA1 = 120,
	MX25_PAD_FEC_RX_DV = 121,
	MX25_PAD_FEC_TX_CLK = 122,
	MX25_PAD_RTCK = 123,
	MX25_PAD_DE_B = 124,
	MX25_PAD_GPIO_A = 125,
	MX25_PAD_GPIO_B = 126,
	MX25_PAD_GPIO_C = 127,
	MX25_PAD_GPIO_D = 128,
	MX25_PAD_GPIO_E = 129,
	MX25_PAD_GPIO_F = 130,
	MX25_PAD_EXT_ARMCLK = 131,
	MX25_PAD_UPLL_BYPCLK = 132,
	MX25_PAD_VSTBY_REQ = 133,
	MX25_PAD_VSTBY_ACK = 134,
	MX25_PAD_POWER_FAIL  = 135,
	MX25_PAD_CLKO = 136,
	MX25_PAD_BOOT_MODE0 = 137,
	MX25_PAD_BOOT_MODE1 = 138,
};

/* Pad names for the pinmux subsystem */
static const struct pinctrl_pin_desc imx25_pinctrl_pads[] = {
	IMX_PINCTRL_PIN(MX25_PAD_RESERVE0),
	IMX_PINCTRL_PIN(MX25_PAD_A10),
	IMX_PINCTRL_PIN(MX25_PAD_A13),
	IMX_PINCTRL_PIN(MX25_PAD_A14),
	IMX_PINCTRL_PIN(MX25_PAD_A15),
	IMX_PINCTRL_PIN(MX25_PAD_A16),
	IMX_PINCTRL_PIN(MX25_PAD_A17),
	IMX_PINCTRL_PIN(MX25_PAD_A18),
	IMX_PINCTRL_PIN(MX25_PAD_A19),
	IMX_PINCTRL_PIN(MX25_PAD_A20),
	IMX_PINCTRL_PIN(MX25_PAD_A21),
	IMX_PINCTRL_PIN(MX25_PAD_A22),
	IMX_PINCTRL_PIN(MX25_PAD_A23),
	IMX_PINCTRL_PIN(MX25_PAD_A24),
	IMX_PINCTRL_PIN(MX25_PAD_A25),
	IMX_PINCTRL_PIN(MX25_PAD_EB0),
	IMX_PINCTRL_PIN(MX25_PAD_EB1),
	IMX_PINCTRL_PIN(MX25_PAD_OE),
	IMX_PINCTRL_PIN(MX25_PAD_CS0),
	IMX_PINCTRL_PIN(MX25_PAD_CS1),
	IMX_PINCTRL_PIN(MX25_PAD_CS4),
	IMX_PINCTRL_PIN(MX25_PAD_CS5),
	IMX_PINCTRL_PIN(MX25_PAD_NF_CE0),
	IMX_PINCTRL_PIN(MX25_PAD_ECB),
	IMX_PINCTRL_PIN(MX25_PAD_LBA),
	IMX_PINCTRL_PIN(MX25_PAD_BCLK),
	IMX_PINCTRL_PIN(MX25_PAD_RW),
	IMX_PINCTRL_PIN(MX25_PAD_NFWE_B),
	IMX_PINCTRL_PIN(MX25_PAD_NFRE_B),
	IMX_PINCTRL_PIN(MX25_PAD_NFALE),
	IMX_PINCTRL_PIN(MX25_PAD_NFCLE),
	IMX_PINCTRL_PIN(MX25_PAD_NFWP_B),
	IMX_PINCTRL_PIN(MX25_PAD_NFRB),
	IMX_PINCTRL_PIN(MX25_PAD_D15),
	IMX_PINCTRL_PIN(MX25_PAD_D14),
	IMX_PINCTRL_PIN(MX25_PAD_D13),
	IMX_PINCTRL_PIN(MX25_PAD_D12),
	IMX_PINCTRL_PIN(MX25_PAD_D11),
	IMX_PINCTRL_PIN(MX25_PAD_D10),
	IMX_PINCTRL_PIN(MX25_PAD_D9),
	IMX_PINCTRL_PIN(MX25_PAD_D8),
	IMX_PINCTRL_PIN(MX25_PAD_D7),
	IMX_PINCTRL_PIN(MX25_PAD_D6),
	IMX_PINCTRL_PIN(MX25_PAD_D5),
	IMX_PINCTRL_PIN(MX25_PAD_D4),
	IMX_PINCTRL_PIN(MX25_PAD_D3),
	IMX_PINCTRL_PIN(MX25_PAD_D2),
	IMX_PINCTRL_PIN(MX25_PAD_D1),
	IMX_PINCTRL_PIN(MX25_PAD_D0),
	IMX_PINCTRL_PIN(MX25_PAD_LD0),
	IMX_PINCTRL_PIN(MX25_PAD_LD1),
	IMX_PINCTRL_PIN(MX25_PAD_LD2),
	IMX_PINCTRL_PIN(MX25_PAD_LD3),
	IMX_PINCTRL_PIN(MX25_PAD_LD4),
	IMX_PINCTRL_PIN(MX25_PAD_LD5),
	IMX_PINCTRL_PIN(MX25_PAD_LD6),
	IMX_PINCTRL_PIN(MX25_PAD_LD7),
	IMX_PINCTRL_PIN(MX25_PAD_LD8),
	IMX_PINCTRL_PIN(MX25_PAD_LD9),
	IMX_PINCTRL_PIN(MX25_PAD_LD10),
	IMX_PINCTRL_PIN(MX25_PAD_LD11),
	IMX_PINCTRL_PIN(MX25_PAD_LD12),
	IMX_PINCTRL_PIN(MX25_PAD_LD13),
	IMX_PINCTRL_PIN(MX25_PAD_LD14),
	IMX_PINCTRL_PIN(MX25_PAD_LD15),
	IMX_PINCTRL_PIN(MX25_PAD_HSYNC),
	IMX_PINCTRL_PIN(MX25_PAD_VSYNC),
	IMX_PINCTRL_PIN(MX25_PAD_LSCLK),
	IMX_PINCTRL_PIN(MX25_PAD_OE_ACD),
	IMX_PINCTRL_PIN(MX25_PAD_CONTRAST),
	IMX_PINCTRL_PIN(MX25_PAD_PWM),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D2),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D3),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D4),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D5),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D6),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D7),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D8),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_D9),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_MCLK),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_VSYNC),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_HSYNC),
	IMX_PINCTRL_PIN(MX25_PAD_CSI_PIXCLK),
	IMX_PINCTRL_PIN(MX25_PAD_I2C1_CLK),
	IMX_PINCTRL_PIN(MX25_PAD_I2C1_DAT),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_MOSI),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_MISO),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_SS0),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_SS1),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_SCLK),
	IMX_PINCTRL_PIN(MX25_PAD_CSPI1_RDY),
	IMX_PINCTRL_PIN(MX25_PAD_UART1_RXD),
	IMX_PINCTRL_PIN(MX25_PAD_UART1_TXD),
	IMX_PINCTRL_PIN(MX25_PAD_UART1_RTS),
	IMX_PINCTRL_PIN(MX25_PAD_UART1_CTS),
	IMX_PINCTRL_PIN(MX25_PAD_UART2_RXD),
	IMX_PINCTRL_PIN(MX25_PAD_UART2_TXD),
	IMX_PINCTRL_PIN(MX25_PAD_UART2_RTS),
	IMX_PINCTRL_PIN(MX25_PAD_UART2_CTS),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_CMD),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_CLK),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_DATA0),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_DATA1),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_DATA2),
	IMX_PINCTRL_PIN(MX25_PAD_SD1_DATA3),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_ROW0),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_ROW1),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_ROW2),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_ROW3),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_COL0),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_COL1),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_COL2),
	IMX_PINCTRL_PIN(MX25_PAD_KPP_COL3),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_MDC),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_MDIO),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_TDATA0),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_TDATA1),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_TX_EN),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_RDATA0),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_RDATA1),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_RX_DV),
	IMX_PINCTRL_PIN(MX25_PAD_FEC_TX_CLK),
	IMX_PINCTRL_PIN(MX25_PAD_RTCK),
	IMX_PINCTRL_PIN(MX25_PAD_DE_B),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_A),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_B),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_C),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_D),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_E),
	IMX_PINCTRL_PIN(MX25_PAD_GPIO_F),
	IMX_PINCTRL_PIN(MX25_PAD_EXT_ARMCLK),
	IMX_PINCTRL_PIN(MX25_PAD_UPLL_BYPCLK),
	IMX_PINCTRL_PIN(MX25_PAD_VSTBY_REQ),
	IMX_PINCTRL_PIN(MX25_PAD_VSTBY_ACK),
	IMX_PINCTRL_PIN(MX25_PAD_POWER_FAIL),
	IMX_PINCTRL_PIN(MX25_PAD_CLKO),
	IMX_PINCTRL_PIN(MX25_PAD_BOOT_MODE0),
	IMX_PINCTRL_PIN(MX25_PAD_BOOT_MODE1),
};

#define PAD_TO_MUX_CTRL_OFS(pad) ((pad & MUX_CTRL_OFS_MASK) >> MUX_CTRL_OFS_SHIFT)
#define PAD_TO_PAD_CTRL_OFS(pad) ((pad & MUX_PAD_CTRL_OFS_MASK) >> MUX_PAD_CTRL_OFS_SHIFT)

#define IMX25_PINCTRL_PIN_REG(pin) { \
	.mux_reg = PAD_TO_MUX_CTRL_OFS(MX25_PAD_##pin##__##pin), \
	.conf_reg = PAD_TO_PAD_CTRL_OFS(MX25_PAD_##pin##__##pin), \
}

static struct imx_pin_reg imx25_pinctrl_regs[] = {
	{0x000, 0x000}, /* PADDING */
	{0x000, 0x000}, /* RESERVE0 */
	IMX25_PINCTRL_PIN_REG(A10),
	IMX25_PINCTRL_PIN_REG(A13),
	IMX25_PINCTRL_PIN_REG(A14),
	IMX25_PINCTRL_PIN_REG(A15),
	IMX25_PINCTRL_PIN_REG(A16),
	IMX25_PINCTRL_PIN_REG(A17),
	IMX25_PINCTRL_PIN_REG(A18),
	IMX25_PINCTRL_PIN_REG(A19),
	IMX25_PINCTRL_PIN_REG(A20),
	IMX25_PINCTRL_PIN_REG(A21),
	IMX25_PINCTRL_PIN_REG(A22),
	IMX25_PINCTRL_PIN_REG(A23),
	IMX25_PINCTRL_PIN_REG(A24),
	IMX25_PINCTRL_PIN_REG(A25),
	IMX25_PINCTRL_PIN_REG(EB0),
	IMX25_PINCTRL_PIN_REG(EB1),
	IMX25_PINCTRL_PIN_REG(OE),
	IMX25_PINCTRL_PIN_REG(CS0),
	IMX25_PINCTRL_PIN_REG(CS1),
	IMX25_PINCTRL_PIN_REG(CS4),
	IMX25_PINCTRL_PIN_REG(CS5),
	IMX25_PINCTRL_PIN_REG(NF_CE0),
	IMX25_PINCTRL_PIN_REG(ECB),
	IMX25_PINCTRL_PIN_REG(LBA),
	IMX25_PINCTRL_PIN_REG(BCLK),
	IMX25_PINCTRL_PIN_REG(RW),
	IMX25_PINCTRL_PIN_REG(NFWE_B),
	IMX25_PINCTRL_PIN_REG(NFRE_B),
	IMX25_PINCTRL_PIN_REG(NFALE),
	IMX25_PINCTRL_PIN_REG(NFCLE),
	IMX25_PINCTRL_PIN_REG(NFWP_B),
	IMX25_PINCTRL_PIN_REG(NFRB),
	IMX25_PINCTRL_PIN_REG(D15),
	IMX25_PINCTRL_PIN_REG(D14),
	IMX25_PINCTRL_PIN_REG(D13),
	IMX25_PINCTRL_PIN_REG(D12),
	IMX25_PINCTRL_PIN_REG(D11),
	IMX25_PINCTRL_PIN_REG(D10),
	IMX25_PINCTRL_PIN_REG(D9),
	IMX25_PINCTRL_PIN_REG(D8),
	IMX25_PINCTRL_PIN_REG(D7),
	IMX25_PINCTRL_PIN_REG(D6),
	IMX25_PINCTRL_PIN_REG(D5),
	IMX25_PINCTRL_PIN_REG(D4),
	IMX25_PINCTRL_PIN_REG(D3),
	IMX25_PINCTRL_PIN_REG(D2),
	IMX25_PINCTRL_PIN_REG(D1),
	IMX25_PINCTRL_PIN_REG(D0),
	IMX25_PINCTRL_PIN_REG(LD0),
	IMX25_PINCTRL_PIN_REG(LD1),
	IMX25_PINCTRL_PIN_REG(LD2),
	IMX25_PINCTRL_PIN_REG(LD3),
	IMX25_PINCTRL_PIN_REG(LD4),
	IMX25_PINCTRL_PIN_REG(LD5),
	IMX25_PINCTRL_PIN_REG(LD6),
	IMX25_PINCTRL_PIN_REG(LD7),
	IMX25_PINCTRL_PIN_REG(LD8),
	IMX25_PINCTRL_PIN_REG(LD9),
	IMX25_PINCTRL_PIN_REG(LD10),
	IMX25_PINCTRL_PIN_REG(LD11),
	IMX25_PINCTRL_PIN_REG(LD12),
	IMX25_PINCTRL_PIN_REG(LD13),
	IMX25_PINCTRL_PIN_REG(LD14),
	IMX25_PINCTRL_PIN_REG(LD15),
	IMX25_PINCTRL_PIN_REG(HSYNC),
	IMX25_PINCTRL_PIN_REG(VSYNC),
	IMX25_PINCTRL_PIN_REG(LSCLK),
	IMX25_PINCTRL_PIN_REG(OE_ACD),
	IMX25_PINCTRL_PIN_REG(CONTRAST),
	IMX25_PINCTRL_PIN_REG(PWM),
	IMX25_PINCTRL_PIN_REG(CSI_D2),
	IMX25_PINCTRL_PIN_REG(CSI_D3),
	IMX25_PINCTRL_PIN_REG(CSI_D4),
	IMX25_PINCTRL_PIN_REG(CSI_D5),
	IMX25_PINCTRL_PIN_REG(CSI_D6),
	IMX25_PINCTRL_PIN_REG(CSI_D7),
	IMX25_PINCTRL_PIN_REG(CSI_D8),
	IMX25_PINCTRL_PIN_REG(CSI_D9),
	IMX25_PINCTRL_PIN_REG(CSI_MCLK),
	IMX25_PINCTRL_PIN_REG(CSI_VSYNC),
	IMX25_PINCTRL_PIN_REG(CSI_HSYNC),
	IMX25_PINCTRL_PIN_REG(CSI_PIXCLK),
	IMX25_PINCTRL_PIN_REG(I2C1_CLK),
	IMX25_PINCTRL_PIN_REG(I2C1_DAT),
	IMX25_PINCTRL_PIN_REG(CSPI1_MOSI),
	IMX25_PINCTRL_PIN_REG(CSPI1_MISO),
	IMX25_PINCTRL_PIN_REG(CSPI1_SS0),
	IMX25_PINCTRL_PIN_REG(CSPI1_SS1),
	IMX25_PINCTRL_PIN_REG(CSPI1_SCLK),
	IMX25_PINCTRL_PIN_REG(CSPI1_RDY),
	IMX25_PINCTRL_PIN_REG(UART1_RXD),
	IMX25_PINCTRL_PIN_REG(UART1_TXD),
	IMX25_PINCTRL_PIN_REG(UART1_RTS),
	IMX25_PINCTRL_PIN_REG(UART1_CTS),
	IMX25_PINCTRL_PIN_REG(UART2_RXD),
	IMX25_PINCTRL_PIN_REG(UART2_TXD),
	IMX25_PINCTRL_PIN_REG(UART2_RTS),
	IMX25_PINCTRL_PIN_REG(UART2_CTS),
	IMX25_PINCTRL_PIN_REG(SD1_CMD),
	IMX25_PINCTRL_PIN_REG(SD1_CLK),
	IMX25_PINCTRL_PIN_REG(SD1_DATA0),
	IMX25_PINCTRL_PIN_REG(SD1_DATA1),
	IMX25_PINCTRL_PIN_REG(SD1_DATA2),
	IMX25_PINCTRL_PIN_REG(SD1_DATA3),
	IMX25_PINCTRL_PIN_REG(KPP_ROW0),
	IMX25_PINCTRL_PIN_REG(KPP_ROW1),
	IMX25_PINCTRL_PIN_REG(KPP_ROW2),
	IMX25_PINCTRL_PIN_REG(KPP_ROW3),
	IMX25_PINCTRL_PIN_REG(KPP_COL0),
	IMX25_PINCTRL_PIN_REG(KPP_COL1),
	IMX25_PINCTRL_PIN_REG(KPP_COL2),
	IMX25_PINCTRL_PIN_REG(KPP_COL3),
	IMX25_PINCTRL_PIN_REG(FEC_MDC),
	IMX25_PINCTRL_PIN_REG(FEC_MDIO),
	IMX25_PINCTRL_PIN_REG(FEC_TDATA0),
	IMX25_PINCTRL_PIN_REG(FEC_TDATA1),
	IMX25_PINCTRL_PIN_REG(FEC_TX_EN),
	IMX25_PINCTRL_PIN_REG(FEC_RDATA0),
	IMX25_PINCTRL_PIN_REG(FEC_RDATA1),
	IMX25_PINCTRL_PIN_REG(FEC_RX_DV),
	IMX25_PINCTRL_PIN_REG(FEC_TX_CLK),
	IMX25_PINCTRL_PIN_REG(RTCK),
	IMX25_PINCTRL_PIN_REG(DE_B),
	IMX25_PINCTRL_PIN_REG(GPIO_A),
	IMX25_PINCTRL_PIN_REG(GPIO_B),
	IMX25_PINCTRL_PIN_REG(GPIO_C),
	IMX25_PINCTRL_PIN_REG(GPIO_D),
	IMX25_PINCTRL_PIN_REG(GPIO_E),
	IMX25_PINCTRL_PIN_REG(GPIO_F),
	IMX25_PINCTRL_PIN_REG(EXT_ARMCLK),
	IMX25_PINCTRL_PIN_REG(UPLL_BYPCLK),
	IMX25_PINCTRL_PIN_REG(VSTBY_REQ),
	IMX25_PINCTRL_PIN_REG(VSTBY_ACK),
	IMX25_PINCTRL_PIN_REG(POWER_FAIL),
	IMX25_PINCTRL_PIN_REG(CLKO),
	IMX25_PINCTRL_PIN_REG(BOOT_MODE0),
	IMX25_PINCTRL_PIN_REG(BOOT_MODE1),
};

#define PAD_TO_MUX_MODE(pad) ((pad & MUX_MODE_MASK) >> MUX_MODE_SHIFT)
#define PAD_TO_SEL_INPUT_OFS(pad) ((pad & MUX_SEL_INPUT_OFS_MASK) >> MUX_SEL_INPUT_OFS_SHIFT)
#define PAD_TO_SEL_INPUT(pad) ((pad & MUX_SEL_INPUT_MASK) >> MUX_SEL_INPUT_SHIFT)
#define PAD_TO_PAD_CTRL(pad) ((pad & MUX_PAD_CTRL_MASK) >> MUX_PAD_CTRL_SHIFT)

#define IMX25_PINCTRL_PIN(_pin, _func) {				\
	.pin = MX25_PAD_##_pin,						\
	.mux_mode = PAD_TO_MUX_MODE(MX25_PAD_##_pin##__##_func),	\
	.input_reg = PAD_TO_SEL_INPUT_OFS(MX25_PAD_##_pin##__##_func),	\
	.input_val = PAD_TO_SEL_INPUT(MX25_PAD_##_pin##__##_func),	\
	.config = PAD_TO_PAD_CTRL(MX25_PAD_##_pin##__##_func),		\
}

/* UART1_RXD */
unsigned int pin_ids_uart1_rxd[] = {
	MX25_PAD_UART1_RXD,
};

struct imx_pin pins_uart1_rxd__uart1_rxd[] = {
	IMX25_PINCTRL_PIN(UART1_RXD, UART1_RXD),
};

/* UART1_TXD */
unsigned int pin_ids_uart1_txd[] = {
	MX25_PAD_UART1_TXD,
};

struct imx_pin pins_uart1_txd__uart1_txd[] = {
	IMX25_PINCTRL_PIN(UART1_TXD, UART1_TXD),
};

/* UART1_RTS */
unsigned int pin_ids_uart1_rts[] = {
	MX25_PAD_UART1_RTS,
};

struct imx_pin pins_uart1_rts__uart1_rts[] = {
	IMX25_PINCTRL_PIN(UART1_RTS, UART1_RTS),
};

/* UART1_CTS */
unsigned int pin_ids_uart1_cts[] = {
	MX25_PAD_UART1_CTS,
};

struct imx_pin pins_uart1_cts__uart1_cts[] = {
	IMX25_PINCTRL_PIN(UART1_CTS, UART1_CTS),
};

/* UART2_RXD */
unsigned int pin_ids_uart2_rxd[] = {
	MX25_PAD_UART2_RXD,
};

struct imx_pin pins_uart2_rxd__uart2_rxd[] = {
	IMX25_PINCTRL_PIN(UART2_RXD, UART2_RXD),
};

/* UART2_TXD */
unsigned int pin_ids_uart2_txd[] = {
	MX25_PAD_UART2_TXD,
};

struct imx_pin pins_uart2_txd__uart2_txd[] = {
	IMX25_PINCTRL_PIN(UART2_TXD, UART2_TXD),
};

/* UART2_RTS */
unsigned int pin_ids_uart2_rts[] = {
	MX25_PAD_UART2_RTS,
};

struct imx_pin pins_uart2_rts__uart2_rts[] = {
	IMX25_PINCTRL_PIN(UART2_RTS, UART2_RTS),
};

/* UART2_CTS */
unsigned int pin_ids_uart2_cts[] = {
	MX25_PAD_UART2_CTS,
};

struct imx_pin pins_uart2_cts__uart2_cts[] = {
	IMX25_PINCTRL_PIN(UART2_CTS, UART2_CTS),
};

/* I2C1_CLK */
unsigned int pin_ids_i2c1_clk[] = {
	MX25_PAD_I2C1_CLK,
};

struct imx_pin pins_i2c1_clk__i2c1_clk[] = {
	IMX25_PINCTRL_PIN(I2C1_CLK, I2C1_CLK),
};

/* I2C1_DAT */
unsigned int pin_ids_i2c1_dat[] = {
	MX25_PAD_I2C1_DAT,
};

struct imx_pin pins_i2c1_dat__i2c1_dat[] = {
	IMX25_PINCTRL_PIN(I2C1_DAT, I2C1_DAT),
};

/* CSPI1_SS1 */
unsigned int pin_ids_cspi1_ss1[] = {
	MX25_PAD_CSPI1_SS1,
};

struct imx_pin pins_cspi1_ss1__gpio_1_17[] = {
	IMX25_PINCTRL_PIN(CSPI1_SS1, GPIO_1_17),
};

/* CSPI1_SCLK */
unsigned int pin_ids_cspi1_sclk[] = {
	MX25_PAD_CSPI1_SCLK,
};

struct imx_pin pins_cspi1_sclk__gpio_1_18[] = {
	IMX25_PINCTRL_PIN(CSPI1_SCLK, GPIO_1_18),
};

/* KPP_COL1 */
unsigned int pin_ids_kpp_col1[] = {
	MX25_PAD_KPP_COL1,
};

struct imx_pin pins_kpp_col1__gpio_3_2[] = {
	IMX25_PINCTRL_PIN(KPP_COL1, GPIO_3_2),
};

/* KPP_COL0 */
unsigned int pin_ids_kpp_col0[] = {
	MX25_PAD_KPP_COL0,
};

struct imx_pin pins_kpp_col0__gpio_3_1[] = {
	IMX25_PINCTRL_PIN(KPP_COL0, GPIO_3_1),
};

#define IMX25_PINCTRL_PIN_GROUP(pin, func) {		\
	.name = __stringify(pin##__##func),		\
	.npins = ARRAY_SIZE(pins_##pin##__##func),	\
	.pin_ids = pin_ids_##pin,			\
	.pins = pins_##pin##__##func,			\
}

static struct imx_pin_group imx25_pinctrl_groups[] = {
	IMX25_PINCTRL_PIN_GROUP(uart1_rxd, uart1_rxd),
	IMX25_PINCTRL_PIN_GROUP(uart1_txd, uart1_txd),
	IMX25_PINCTRL_PIN_GROUP(uart1_rts, uart1_rts),
	IMX25_PINCTRL_PIN_GROUP(uart1_cts, uart1_cts),
	IMX25_PINCTRL_PIN_GROUP(uart2_rxd, uart2_rxd),
	IMX25_PINCTRL_PIN_GROUP(uart2_txd, uart2_txd),
	IMX25_PINCTRL_PIN_GROUP(uart2_rts, uart2_rts),
	IMX25_PINCTRL_PIN_GROUP(uart2_cts, uart2_cts),
	IMX25_PINCTRL_PIN_GROUP(i2c1_clk, i2c1_clk),
	IMX25_PINCTRL_PIN_GROUP(i2c1_dat, i2c1_dat),
	IMX25_PINCTRL_PIN_GROUP(cspi1_ss1, gpio_1_17),
	IMX25_PINCTRL_PIN_GROUP(cspi1_sclk, gpio_1_18),
	IMX25_PINCTRL_PIN_GROUP(kpp_col1, gpio_3_2),
	IMX25_PINCTRL_PIN_GROUP(kpp_col0, gpio_3_1),
};

static const char *uart1_groups[] = {
	"uart1_rxd__uart1_rxd",
	"uart1_txd__uart1_txd",
	"uart1_rts__uart1_rts",
	"uart1_cts__uart1_cts",
};

static const char *uart2_groups[] = {
	"uart2_rxd__uart2_rxd",
	"uart2_txd__uart2_txd",
	"uart2_rts__uart2_rts",
	"uart2_cts__uart2_cts",
};

static const char *i2c1_groups[] = {
	"i2c1_clk__i2c1_clk",
	"i2c1_dat__i2c1_dat",
};

static const char *i2c_gpio3_groups[] = {
	"cspi1_ss1__gpio_1_17",
	"cspi1_sclk__gpio_1_18",
};

static const char *i2c_gpio4_groups[] = {
	"kpp_col1__gpio_3_2",
	"kpp_col0__gpio_3_1",
};

#define IMX25_PINCTRL_PMX_FUNC(func) {			\
	.name = __stringify(func),			\
	.groups = func##_groups,			\
	.num_groups = ARRAY_SIZE(func##_groups),	\
}

static struct imx_pmx_func imx25_pinctrl_functions[] = {
	IMX25_PINCTRL_PMX_FUNC(uart1),
	IMX25_PINCTRL_PMX_FUNC(uart2),
	IMX25_PINCTRL_PMX_FUNC(i2c1),
	IMX25_PINCTRL_PMX_FUNC(i2c_gpio3),
	IMX25_PINCTRL_PMX_FUNC(i2c_gpio4),
};

static struct imx_pinctrl_soc_info imx25_pinctrl_info = {
	.pins = imx25_pinctrl_pads,
	.npins = ARRAY_SIZE(imx25_pinctrl_pads),
	.pin_regs = imx25_pinctrl_regs,
	.groups = imx25_pinctrl_groups,
	.ngroups = ARRAY_SIZE(imx25_pinctrl_groups),
	.functions = imx25_pinctrl_functions,
	.nfunctions = ARRAY_SIZE(imx25_pinctrl_functions),
};

static struct of_device_id imx25_pinctrl_of_match[] = {
	{ .compatible = "fsl,imx25-iomuxc", },
	{ /* sentinel */ }
};

static int imx25_pinctrl_probe(struct platform_device *pdev)
{
	return imx_pinctrl_probe(pdev, &imx25_pinctrl_info);
}

static struct platform_driver imx25_pinctrl_driver = {
	.driver = {
		.name = "imx25-pinctrl",
		.owner = THIS_MODULE,
		.of_match_table = of_match_ptr(imx25_pinctrl_of_match),
	},
	.probe = imx25_pinctrl_probe,
	.remove = imx_pinctrl_remove,
};

static int __init imx25_pinctrl_init(void)
{
	return platform_driver_register(&imx25_pinctrl_driver);
}
arch_initcall(imx25_pinctrl_init);

static void __exit imx25_pinctrl_exit(void)
{
	platform_driver_unregister(&imx25_pinctrl_driver);
}
module_exit(imx25_pinctrl_exit);
MODULE_AUTHOR("Denis Carikli <denis@eukrea.com>");
MODULE_DESCRIPTION("Freescale IMX25 pinctrl driver");
MODULE_LICENSE("GPL v2");
